title = "mxplusb"
baseURL = "http://example.org/"
languageCode = "en-us"
theme = "hugo-cactus-theme"
publishDir = "docs"


[params]
    name = "mxplusb"
	description = ""
	bio = "Let's be honest, I just fiddle with random bits of code."
#    custom_js = ["sigma.js", "plugins/sigma.parsers.json.min.js"]
    # Enter optionally your twitter account
    # twitter = ""
    enableRSS = true

    # Add custom assets with their paths relative to the static folder
    customCSS = []
#    customJS  = ["sigma.js"]

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = "There's No Place Like /"
    about = "A Really Long Arbitrary Title For A Page About Me"
    subscribe = "RSS"
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = "Copyright 2017 Mike Lloyd"
    # Sharing options and author information in posts
    aboutAuthor = "I just fiddle with random bits of code."
    tweet = ""
    share = ""
    # 404 page
    title404 = ""
    subtitle404 = ""

    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

[social]
    github   = "https://www.github.com/mxplusb"